server:
  port: 9005
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vikeyliu/config-repo.git
          search-paths:
          - config-repo

        label: master
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    #配置47.110.126.42
    prefer-ip-address: true
    ip-address: 192.168.1.210
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}

  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8005/eureka/


